import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { enterpriseFiles } from '../tools/build-enterprise-package.mjs';
const source = '// @version      1.17.0\n(() => { window.example = true; })();\n';
const base = { origins: ['https://tessa.example.test'] };
const files = enterpriseFiles(source, base);
const manifest = JSON.parse(files.get('extension/manifest.json'));
assert.equal(manifest.manifest_version, 3);
assert.equal(manifest.content_scripts[0].world, 'MAIN');
assert.deepEqual(manifest.content_scripts[0].matches, ['https://tessa.example.test/*']);
for (const field of ['permissions', 'host_permissions', 'background', 'web_accessible_resources', 'externally_connectable']) assert.equal(manifest[field], undefined);
assert.equal(files.get('extension/studio.js'), source);
assert.equal(files.has('update.xml'), false);
assert.equal(JSON.parse(files.get('BUILD.json')).sourceSha256, crypto.createHash('sha256').update(source).digest('hex'));
for (const origin of ['http://tessa.example.test', 'https://*.example.test', '<all_urls>', 'https://user:pass@example.test', 'https://example.test/path', 'https://example.test/#x', 'https://example.test:8443', 'https://example.test\\evil']) assert.throws(() => enterpriseFiles(source, { origins: [origin] }));
assert.throws(() => enterpriseFiles(source, { origins: [] }));
assert.throws(() => enterpriseFiles(source, { ...base, updateUrl: 'https://updates.example.test/update.xml' }));
const config = { ...base, extensionId: 'abcdefghijklmnopabcdefghijklmnop', updateUrl: 'https://updates.example.test/update.xml', crxUrl: 'https://updates.example.test/studio.crx?a=1&b=2' };
const updated = enterpriseFiles(source, config);
assert.match(updated.get('update.xml'), /a=1&amp;b=2/);
assert.equal(JSON.parse(updated.get('policy/ExtensionSettings.json'))[config.extensionId].override_update_url, true);
assert.throws(() => enterpriseFiles(source, { ...config, crxUrl: 'http://updates.example.test/file.crx' }));
assert.throws(() => enterpriseFiles(source, { ...config, extensionId: 'x'.repeat(32) }));
assert.throws(() => enterpriseFiles(source.replace('1.17.0', '01.17.0'), base));
console.log('Enterprise package: exact static source, narrow origins, no privileged permissions, validated updates and deterministic checksums OK');
